version: "3.9"

services:
  api:
    build: .
    depends_on:
      - mongodb
    environment:
      PORT: 2392
      JWT_SECRET: sdn93u94ojewe
      DB_URL: mongodb://main:root@mongodb:27017
    ports:
      - "2392:2392"

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: main
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
